export const series = [
  {
    name: "Casa de papel",
    description:
      "Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.",
    categories: ["Suspenso", "Emocionante", "De intriga"],
    seasons: 5,
    recommendation: 90,
    date: 2021,
    cast: ["Úrsula Corberó", "Alvaro Morte", "Itziar Ituño"],
    genders: ["De España", "Series sobre crímenes", "Thrillers de TV"],
    miniature: "casapapel.jpg",
  },
  {
    name: "Los 100",
    description:
      "Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.",
    categories: ["Suspenso", "Emocionante", "De intriga"],
    seasons: 5,
    recommendation: 90,
    date: 2021,
    cast: ["Úrsula Corberó", "Alvaro Morte", "Itziar Ituño"],
    genders: ["De España", "Series sobre crímenes", "Thrillers de TV"],
    miniature: "100.webp",
  },
  {
    name: "Breaking Bad",
    description:
      "Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.",
    categories: ["Suspenso", "Emocionante", "De intriga"],
    seasons: 5,
    recommendation: 90,
    date: 2021,
    cast: ["Úrsula Corberó", "Alvaro Morte", "Itziar Ituño"],
    genders: ["De España", "Series sobre crímenes", "Thrillers de TV"],
    miniature: "breaking-bad.webp",
  },
  {
    name: "Kindom",
    description:
      "Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.",
    categories: ["Suspenso", "Emocionante", "De intriga"],
    seasons: 5,
    recommendation: 90,
    date: 2021,
    cast: ["Úrsula Corberó", "Alvaro Morte", "Itziar Ituño"],
    genders: ["De España", "Series sobre crímenes", "Thrillers de TV"],
    miniature: "kindom.jpg",
  },
  {
    name: "La ley de los Audaces",
    description:
      "Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.",
    categories: ["Suspenso", "Emocionante", "De intriga"],
    seasons: 5,
    recommendation: 90,
    date: 2021,
    cast: ["Úrsula Corberó", "Alvaro Morte", "Itziar Ituño"],
    genders: ["De España", "Series sobre crímenes", "Thrillers de TV"],
    miniature: "leyauda.webp",
  },
  {
    name: "Manifesto",
    description:
      "Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.",
    categories: ["Suspenso", "Emocionante", "De intriga"],
    seasons: 5,
    recommendation: 90,
    date: 2021,
    cast: ["Úrsula Corberó", "Alvaro Morte", "Itziar Ituño"],
    genders: ["De España", "Series sobre crímenes", "Thrillers de TV"],
    miniature: "manifesto.jpg",
  },
  {
    name: "Pablo Escobar",
    description:
      "Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.",
    categories: ["Suspenso", "Emocionante", "De intriga"],
    seasons: 5,
    recommendation: 90,
    date: 2021,
    cast: ["Úrsula Corberó", "Alvaro Morte", "Itziar Ituño"],
    genders: ["De España", "Series sobre crímenes", "Thrillers de TV"],
    miniature: "pabloe.webp",
  },
  {
    name: "Peaky blinders",
    description:
      "Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.",
    categories: ["Suspenso", "Emocionante", "De intriga"],
    seasons: 5,
    recommendation: 90,
    date: 2021,
    cast: ["Úrsula Corberó", "Alvaro Morte", "Itziar Ituño"],
    genders: ["De España", "Series sobre crímenes", "Thrillers de TV"],
    miniature: "peaky.jpg",
  },
  {
    name: "Vis a Vis",
    description:
      "Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.",
    categories: ["Suspenso", "Emocionante", "De intriga"],
    seasons: 5,
    recommendation: 90,
    date: 2021,
    cast: ["Úrsula Corberó", "Alvaro Morte", "Itziar Ituño"],
    genders: ["De España", "Series sobre crímenes", "Thrillers de TV"],
    miniature: "visavis.jpg",
  },
];
